mysql:
  host: '127.0.0.1'
  port: 3306
  username: 'root'
  password: 'root123456'
spring:
  datasource:
    url: "jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false"
    username: root
    password: ${mysql.password}
    driverClassName: com.mysql.jdbc.Driver
---
spring:
  profiles: dev
mysql:
  host: mysql
---
spring:
  profiles: prod
mysql:
  host: mysql
---
spring:
  profiles: test
mysql:
  host: mysql
---
spring:
  profiles: local

mysql:
  host: localhost
  password: 'Qweqwe#24'
